server:
  servlet:
    session:
      timeout: 10m
  #  servlet:
#    context-path: /security-session
  port: 8080
logging:
  level:
    org:
      springframework:
        security: debug
        session: debug