server:
  servlet:
    session:
      timeout: 10s
      cookie:
        max-age: 10s
        name: session-test
#    servlet:
#    context-path: /security-session
  port: 8080
spring:
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org:
      springframework:
        security: debug
        session: debug